package cn.apier.app.ytask.common

/**
 * Created by yanjunhua on 2017/9/20.
 */

class SpeechConstant {
    companion object {
        val ASR_START = "asr.start"
        val ASR_STOP = "asr.stop"
        val ASR_CANCEL = "asr.cancel"
        val ASR_KWS_LOAD_ENGINE = "asr.kws.load"
        val ASR_KWS_UNLOAD_ENGINE = "asr.kws.unload"
        val ASR_UPLOAD_WORDS = "asr.upload.words"
        val ASR_UPLOAD_CANCEL = "asr.upload.cancel"
        val WAKEUP_START = "wp.start"
        val WAKEUP_STOP = "wp.stop"
        val WAKEUP_LOAD_ENGINE = "wp.load"
        val WAKEUP_UNLOAD_ENGINE = "wp.unload"
        val ASR_UPLOAD_CONTRACT = "asr.upload.contract"
        val UPLOADER_START = "uploader.start"
        val UPLOADER_CANCEL = "uploader.cancel"
        val CALLBACK_EVENT_ASR_READY = "asr.ready"
        val CALLBACK_EVENT_ASR_BEGIN = "asr.begin"
        val CALLBACK_EVENT_ASR_AUDIO = "asr.audio"
        val CALLBACK_EVENT_ASR_VOLUME = "asr.volume"
        val CALLBACK_EVENT_ASR_END = "asr.end"
        val CALLBACK_EVENT_ASR_PARTIAL = "asr.partial"
        val CALLBACK_EVENT_ASR_FINISH = "asr.finish"
        val CALLBACK_EVENT_ASR_EXIT = "asr.exit"
        val CALLBACK_EVENT_ASR_CANCEL = "asr.cancel"
        val CALLBACK_EVENT_ASR_ERROR = "asr.error"
        val CALLBACK_EVENT_ASR_LOADED = "asr.loaded"
        val CALLBACK_EVENT_ASR_UNLOADED = "asr.unloaded"
        val CALLBACK_EVENT_ASR_SERIALNUMBER = "asr.sn"
        val CALLBACK_EVENT_ASR_LOG = "asr.log"
        val CALLBACK_EVENT_UPLOAD_COMPLETE = "asr.upload.complete"
        val CALLBACK_EVENT_ASR_LONG_SPEECH = "asr.long-speech.finish"
        val ASR_CALLBACk_NAME = "ASR.callback"
        val WAKEUP_CALLBACK_NAME = "WAKEUP.callback"
        val UPLOAD_CALLBACK_NAME = "UPLOAD.callback"
        val CALLBACK_ASR_STATUS = "cb.asr.status.int"
        val strCALLBACK_ASR_LEVEL = "cb.asr.level.int"
        val CALLBACK_ASR_RESULT = "cb.asr.result.string"
        val CALLBACK_WAK_STATUS = "cb.wak.status.int"
        val CALLBACK_WAK_RESULT = "cb.wak.result.string"
        val CALLBACK_ERROR_DOMAIN = "cb.error.domain.int16_t"
        val CALLBACK_ERROR_CODE = "cb.error.code.int16_t"
        val CALLBACK_ERROR_DESC = "cb.error.desc.string"
        val SOUND_START = "sound_start"
        val SOUND_END = "sound_end"
        val SOUND_SUCCESS = "sound_success"
        val SOUND_ERROR = "sound_error"
        val SOUND_CANCEL = "sound_cancel"
        val CALLBACK_EVENT_WAKEUP_STARTED = "wp.enter"
        val CALLBACK_EVENT_WAKEUP_READY = "wp.ready"
        val CALLBACK_EVENT_WAKEUP_STOPED = "wp.exit"
        val CALLBACK_EVENT_WAKEUP_LOADED = "wp.loaded"
        val CALLBACK_EVENT_WAKEUP_UNLOADED = "wp.unloaded"
        val CALLBACK_EVENT_WAKEUP_ERROR = "wp.error"
        val CALLBACK_EVENT_WAKEUP_SUCCESS = "wp.data"
        val CALLBACK_EVENT_WAKEUP_AUDIO = "wp.audio"
        val CALLBACK_EVENT_UPLOAD_FINISH = "uploader.finish"
        val LOG_LEVEL = "log_level"
        val LANGUAGE = "language"
        val CONTACT = "contact"
        val VAD = "vad"
        val VAD_MFE = "mfe"
        val VAD_MODEL = "model-vad"
        val VAD_DNN = "dnn"
        val VAD_TOUCH = "touch"
        val SAMPLE_RATE = "sample"
        val PAM = "decoder-server.pam"
        val NLU = "nlu"
        val PROP = "prop"
        var PUBLIC_DECODER = false
        val IN_FILE = "infile"
        val AUDIO_MILLS = "audio.mills"
        val AUDIO_SOURCE = "audio.source"
        val OUT_FILE = "outfile"
        val ACCEPT_AUDIO_DATA = "accept-audio-data"
        val ACCEPT_AUDIO_VOLUME = "accept-audio-volume"
        val APP_KEY = "key"
        val SECRET = "secret"
        val URL = "decoder-server.url"
        val PID = "pid"
        val APP_NAME = "decoder-server.app"
        val URL_NEW = "https://vse.baidu.com/v2"
        val URL_OLD = "https://vse.baidu.com/echo.fcgi"
        val DEC_TYPE = "dec-type"
        val DECODER = "decoder"
        val ASR_VAD_RES_FILE_PATH = "vad.res-file"
        val VAD_ENDPOINT_TIMEOUT = "vad.endpoint-timeout"
        val ASR_OFFLINE_ENGINE_GRAMMER_FILE_PATH = "grammar"
        val ASR_OFFLINE_ENGINE_DAT_FILE_PATH = "asr-base-file-path"
        val ASR_OFFLINE_ENGINE_LICENSE_FILE_PATH = "license-file-path"
        val SLOT_DATA = "slot-data"
        val DISABLE_PUNCTUATION = "disable-punctuation"
        val KWS_TYPE = "kws-type"
        val APP_ID = "appid"
        val WP_DAT_FILEPATH = "wakeup_dat_filepath"
        val WP_WORDS_FILE = "kws-file"
        val WP_WORDS = "words"
        val WP_ENGINE_LICENSE_FILE_PATH = "license-file-path"
    }
}
